---

  name: crontab
  hosts: all
  
  tasks:

  - name: Enviar Scripts
    shell: mkdir /Scripts/Ultima
    copy:
      src: /home/Scripts/Ultima
      dest: /home/Scripts/Ultima
    become: yes

  - cron:
      name: "Run RespaldoSemanalGenerico.sh"
      minute: "0"
      hour: "1"
      weekday: "6"
      job: "/home/Scripts/Ultima/RespaldoSemanalGenerico.sh "
      cron_file: RespaldoSemanal 
  
  - cron:
      name: "Run SambaBackup.sh"
      minute: "0"
      hour: "1"
      weekday: "0-5"
      job: "/home/Scripts/Ultima/SambaBackup.sh "
      cron_file: RespaldoSamba 
  
  - name: samba
    yum:
      name: samba
      state: latest

  - name: Habilitar samba
    ansible.builtin.systemd:
      name: smb.service
      enabled: yes
    become: yes

  - name: Habilita samba
    ansible.builtin.systemd:
      name: nmb.service
      enabled: yes
    become: yes